#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.4.11f1_2d9804dddde7"
#define UNITY_VERSION_FULL_NICE "2019.4.11f1 (2d9804dddde7)"
#define UNITY_VERSION_BLD 2988036
#define UNITY_VERSION_DATE 1600779566
#define UNITY_VERSION_WIN "2019.4.11.2988036"
#define UNITY_VERSION_BRANCH "2019.4/staging"
